package com.sysecho.mysleep.voice.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.github.pagehelper.Page;
import com.sysecho.mysleep.voice.entity.Voice;

@Mapper
public interface VoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbg.generated
     */
    int insert(Voice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbg.generated
     */
    Voice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbg.generated
     */
    Page<Voice> selectAll();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Voice record);
}